name: todo

services:
  api:
    build:
      context: ./todo
    volumes:
      - ./todo:/code # Sync local development directory with the container
    depends_on:
      - postgres_db
    ports:
      - "8000:8000" # Expose container port 8000 to host port 8000
    networks:
      - net
  postgres_db:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: todo_postgresql_container
    environment:
      - POSTGRES_USER=fuzail
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - net
volumes:
  postgres_db:
    driver: local
networks:
  net: # Define the custom network
